### ISSUE TITLE
Two errors but they happen concurrently.

### ISSUE THREAD

**Issue by thogan44** [ventrian/News-Articles#44]
**first a module load exception..**
ModuleId:2616

ModuleDefId:261

FriendlyName:DnnForge - NewsArticles

ModuleControlSource:DesktopModules/DnnForge - NewsArticles/NewsArticles.ascx

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:5a4eb8a4-f540-4d36-a5a7-610a5ab8bd17

AssemblyVersion:9.2.2

PortalId:4

UserId:1

TabId:975

RawUrl:/News/In-The-News/ViewArticle/ID/1210/Budget-based-storage-designredesign-doesnt-have-to-be-cost-confining.aspx

Referrer:https://intalere2020.localhost/News/In-The-News/ViewArticle/def/ErrorMessage.aspx

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

ExceptionHash:DbJKuoNYXhaub2KR5Ora1k0E1KI=

Message:D:\web\DotNetNuke\DesktopModules\DnnForge - NewsArticles\Controls\PostComment.ascx(30): error BC30560: 'desktopmodules_dnnforge___newsarticles_controls_recaptcha_ascx' is ambiguous in the namespace 'ASP'.

StackTrace:

InnerMessage:D:\web\DotNetNuke\DesktopModules\DnnForge - NewsArticles\Controls\PostComment.ascx(30): error BC30560: 'desktopmodules_dnnforge___newsarticles_controls_recaptcha_ascx' is ambiguous in the namespace 'ASP'.

InnerStackTrace:

at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at Ventrian.NewsArticles.LayoutController.ProcessArticleItem(ControlCollection& objPlaceHolder, String[] layoutArray, ArticleInfo objArticle) at Ventrian.NewsArticles.ViewArticle.BindArticle() at Ventrian.NewsArticles.ViewArticle.Page_Initialization(Object sender, EventArgs e)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

**Then a Page Load Exception..**
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:9c8b8467-e58d-43f3-b5c4-497e7ab75504

AssemblyVersion:9.2.2

PortalId:4

UserId:1

TabId:975

RawUrl:/News/In-The-News/ViewArticle/ID/1210/Budget-based-storage-designredesign-doesnt-have-to-be-cost-confining.aspx

Referrer:https://intalere2020.localhost/News/In-The-News/ViewArticle/def/ErrorMessage.aspx

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

ExceptionHash:3RLbn4nIup0lpMlpILtArrVGO/E=

Message:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).

StackTrace:

InnerMessage:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).

InnerStackTrace:

at System.Web.UI.ControlCollection.Add(Control child) at DotNetNuke.Services.Exceptions.Exceptions.ProcessModuleLoadException(String FriendlyMessage, Control ctrl, Exception exc, Boolean DisplayErrorMessage)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

I did go and download your solution to see if I can get to the bottom of why this is breaking like this.
The module specifically is..
DnnForge - NewsArticles 0.11.1

**Comment by thogan44** [comment]
I disable the ability to comment but if we need this in the future we may want this to work.

**Comment by b-creative** [comment]
Have you tried all Captcha types in the Main Options > Comment settings?

**Comment by thogan44** [comment]
I did the one that we were referencing was DNN core since we never had an api key for the other captchas

**Comment by b-creative** [comment]
Maybe try the two others?

**Comment by Timo-Breumelhof** [comment]
AFAIK this is an issue in the core Captcha

**Comment by Timo-Breumelhof** [comment]
I'm marking this as Won't fix as it's an issue in the core IMO and not the module.
