### ISSUE TITLE
upload of webp file type fails

### ISSUE THREAD

**Issue by in8dna** [ventrian/News-Articles#84]
This might not be true for  DNN 9, but it is an issue with NA 11.3 on DNN 8.04.

When I try to upload a webp file-type in news articles to attach the image to an article, I get an uploader error. I have added the mime-type into the webconfig, and can upload and view the file-type with the DNN file manager. But I cannot view the webp file-types in the NA 'attach files from an existing file location' with the drop-down selector in NA. The webp file-types are not listed.

THe event log error is:

InnerMessage:Parameter is not valid.

InnerStackTrace:

   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at Ventrian.NewsArticles.Controls.UploadImages.btUpload_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Is this still an issue with NA 13, or just in DNN 8?

**Comment by Timo-Breumelhof** [comment]
I guess it's an issue with NA
